name: Build Ionic App and Deploy on FTP

on:
  push:
    branches:
      - main # Adjust this to your branch name if needed

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker Image
        run: docker build -t usamashafique/school_health_app_image:latest .
      
      - name: Push Docker Image
        run: docker push usamashafique/school_health_app_image:latest